# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_core_helper_function": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mjboothaus.github.io/titanic_nbdev/"

git_url = "https://github.com/mjboothaus/titanic_nbdev/tree/master/"

def custom_doc_links(name): return None
