# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_core_helper_function": "00_core.ipynb",
         "TITANIC_DATA_FILE": "88_app.ipynb",
         "AUTHOR_INFO": "88_app.ipynb",
         "APP_NAME": "88_app.ipynb",
         "SideBar": "88_app.ipynb",
         "create_sidebar": "88_app.ipynb",
         "create_mainscreen": "88_app.ipynb",
         "sb": "88_app.ipynb"}

modules = ["core.py",
           "app.py"]

doc_url = "https://mjboothaus.github.io/titanic_nbdev/"

git_url = "https://github.com/mjboothaus/titanic_nbdev/tree/master/"

def custom_doc_links(name): return None
